export enum MessageTypeEnum {
    NEW_CHAT = "NEW_CHAT",
    NEW_ORDER = "NEW_ORDER",
    MESSAGE = "MESSAGE",
    MESSAGE_FROM_CUSTOMER = "MESSAGE_FROM_CUSTOMER",
    SYSTEM_MESSAGE = "SYSTEM_MESSAGE"
}