export enum OrderStatusEnum {
    CREATED = "CREATED",
    DISTRIBUTION = "DISTRIBUTION",
    ADMIN_REVIEW = "ADMIN_REVIEW",
    IN_PROGRESS = "IN_PROGRESS",
    REVIEW = "REVIEW",
    GUARANTEE = "GUARANTEE",
    FINALIZATION = "FINALIZATION",
    CLOSED = "CLOSED"
}