spring:
  servlet:
    multipart:
      max-request-size: 128MB
      max-file-size: 128MB
  session:
    timeout: 5259600

  mvc:
    async:
      request-timeout: 120s

  datasource:
    hikari:
      maximum-pool-size: 60
      max-lifetime: 100000
      validationTimeout: 10000
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:localDB}
    password: ${DB_PASSWORD:localPS}
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:5432/local}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
aws:
  aws_access_key_id: ${aws_access_key_id}
  aws_secret_access_key: ${aws_secret_access_key}

vapid:
  public:
    key: ${VAPID_PUBLIC_KEY}
  private:
    key: ${VAPID_PRIVATE_KEY}

telegram:
  bot_token: ${bot_token}

ai:
  url: ${AI_URL}

server:
  port: 8081
  servlet:
    session:
      timeout: 5259600
      cookie:
        max-age: 5259600
        name: JSESSIONID