spring:
  application:
    name: forward-system
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:localDB}
    password: ${DB_PASSWORD:localPS}
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:5432/local}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8081