services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8081"
    profiles:
      - production
      - yandex
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - production
      - yandex
    environment:
      TZ: Europe/Moscow
      LETSENCRYPT: true
      LE_EMAIL: ${LE_EMAIL}
      LE_FQDN: ${LE_DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: local
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./local-db-data:/var/lib/postgresql/data/pgdata
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    profiles:
      - dependency
      - production

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    profiles:
      - dependency
      - production