services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8081"
    profiles:
      - production
      - yandex
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: local
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./local-db-data:/var/lib/postgresql/data/pgdata
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    profiles:
      - dependency
      - production

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    profiles:
      - dependency
      - production