services:

  app-server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: app-server
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '4g'
        reservations:
          cpus: '0.5'
          memory: '2g'
    cpuset: "0-2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8081"
    profiles:
      - production
      - yandex
    networks:
      - nginx-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - production
      - yandex
    environment:
      TZ: Europe/Moscow
      LETSENCRYPT: true
      LE_EMAIL: ${LE_EMAIL}
      LE_FQDN: ${LE_DOMAIN}
    networks:
      - nginx-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: local
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./local-db-data:/var/lib/postgresql/data/pgdata
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    profiles:
      - dependency
      - production

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
    networks:
      - nginx-net
    profiles:
      - yandex
      - production

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    profiles:
      - dependency
      - production

networks:
  nginx-net:
    driver: bridge