services:
  app-server:
    image: forward-system:latest
    container_name: app-server
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '6g'
        reservations:
          cpus: '1.0'
          memory: '4g'
    cpuset: "0-2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8081"
    profiles:
      - production
      - yandex
    networks:
      - nginx-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - production
      - yandex
    environment:
      TZ: Europe/Moscow
      LETSENCRYPT: true
      LE_EMAIL: ${LE_EMAIL}
      LE_FQDN: ${LE_DOMAIN}
    networks:
      - nginx-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: local
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./local-db-data:/var/lib/postgresql/data/pgdata
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    profiles:
      - dependency
      - production

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
    networks:
      - nginx-net
    profiles:
      - yandex
      - production

  broker-dev:
    image: apache/kafka:latest
    container_name: broker-dev
    hostname: "kafka"
    restart: always
    networks:
      - nginx-net
    volumes:
      - ./kafka_data:/tmp/kafka-logs
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_BYTES: 1048576
      KAFKA_NUM_PARTITIONS: 3
    profiles:
      - dependency

  broker-prod:
    image: apache/kafka:latest
    container_name: broker
    hostname: "kafka"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2g'
        reservations:
          cpus: '0.5'
          memory: '1g'
    cpuset: "0-2"
    networks:
      - nginx-net
    volumes:
      - ./kafka_data:/tmp/kafka-logs
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_BYTES: 1048576
      KAFKA_NUM_PARTITIONS: 3
    profiles:
      - production
      - yandex

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - nginx-net
    profiles:
      - production
      - yandex
      - dependency

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    profiles:
      - dependency
      - production

networks:
  nginx-net:
    driver: bridge