name: Deploy to server

on:
  push:
    tags:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /usr/src/forward-system
            git pull

      - name: Build image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /usr/src/forward-system
            docker build -f ./docker/Dockerfile . --tag forward-system:latest

      - name: Docker compose start
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /usr/src/forward-system/docker
            docker compose down
            docker compose --profile yandex up -d --build
